// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DrawInterfaceClient is the client API for DrawInterface service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DrawInterfaceClient interface {
}

type drawInterfaceClient struct {
	cc grpc.ClientConnInterface
}

func NewDrawInterfaceClient(cc grpc.ClientConnInterface) DrawInterfaceClient {
	return &drawInterfaceClient{cc}
}

// DrawInterfaceServer is the server API for DrawInterface service.
// All implementations must embed UnimplementedDrawInterfaceServer
// for forward compatibility
type DrawInterfaceServer interface {
	mustEmbedUnimplementedDrawInterfaceServer()
}

// UnimplementedDrawInterfaceServer must be embedded to have forward compatible implementations.
type UnimplementedDrawInterfaceServer struct {
}

func (UnimplementedDrawInterfaceServer) mustEmbedUnimplementedDrawInterfaceServer() {}

// UnsafeDrawInterfaceServer may be embedded to opt out of forward compatibility for this service.
// Use of this server is not recommended, as added methods to DrawInterfaceServer will
// result in compilation errors.
type UnsafeDrawInterfaceServer interface {
	mustEmbedUnimplementedDrawInterfaceServer()
}

func RegisterDrawInterfaceServer(s grpc.ServiceRegistrar, srv DrawInterfaceServer) {
	s.RegisterService(&DrawInterface_ServiceDesc, srv)
}

// DrawInterface_ServiceDesc is the grpc.ServiceDesc for DrawInterface service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DrawInterface_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "draw.server.v1.DrawInterface",
	HandlerType: (*DrawInterfaceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "draw_interface.proto",
}
